version: '3'

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        networks:
            - prometheus_net
        restart: unless-stopped

    prometheus-exporter-cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.45.0
        container_name: prometheus-exporter-cadvisor
        ports:
            - "9089:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro 
            - /dev/disk/:/dev/disk:ro
        networks:
            - prometheus_net
        depends_on:
            - prometheus
        devices:
            - /dev/kmsg
        privileged: true
        restart: unless-stopped

    grafana:
        image: grafana/grafana-oss
        container_name: grafana      
        ports:
            - "9080:3000"
        volumes:
            - grafana_data:/var/lib/grafana
        networks:
            - prometheus_net
        depends_on:
            - prometheus
        restart: unless-stopped

networks:
    prometheus_net:
        driver: bridge

volumes:
    prometheus_data:
        driver: local
    grafana_data:
        driver: local