version: "3"

services:
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '8888:80'
        volumes:
            - 'pihole_data:/etc/pihole'
            - 'pihole_dns:/etc/dnsmasq.d'
        environment:
            TZ: ${TIMEZONE}
        restart: unless-stopped

volumes:
    pihole_data:
        driver: local
    pihole_dns:
        driver: local
